### ISSUE TITLE
Interrupt handling

### ISSUE THREAD

**Issue by alsaleem00** [juhovh/esp-i2c#1]
How the code survive communication if interrupt happens?

**Comment by alsaleem00** [comment]
Sorry, I did not notice the interrupt disable code. you can close.

**Comment by juhovh** [comment]
Well the interrupt disable code is only used during startup when setting the GPIO pins into the correct mode. There is still a chance that an interrupt will mess up timings during read or write, therefore if you want to be absolutely sure you might want to disable interrupts manually during read and write as well.

Sorry that the documentation is a bit lacking, but at least the code should be quite clear and readable.

**Comment by alsaleem00** [comment]
Thanks. that's what I am planning to do (disable interrupt on read/write).
