### ISSUE TITLE
__gpiomux, __gpiofunc size

### ISSUE THREAD

**Issue by alsaleem00** [juhovh/esp-i2c#2]
The const array:
`static uint8 __gpiomux[16] = {`

should be uint32 type?
`static uint32 __gpiomux[16] = {`

regards,

**Comment by juhovh** [comment]
You are correct that all the values are of type uint32, but when they are assigned to the uint8 array they are truncated to the one least significant byte, which is the GPIO mux index. Then `PERIPHS_IO_MUX_GPIO` macro adds the `PERIPHS_IO_MUX` address back to it and returns it to the original value, meaning the code should work just fine.

I guess I could change it for clarity, but then again the "if it ain't broken, don't fix it" principle would suggest we can keep it as it is, unless you are having any issues with the code?

**Comment by alsaleem00** [comment]
The compiler gives me error and could not go further even it works with uint8. 
(with treat warning as error.)

**Comment by juhovh** [comment]
I guess that's a good enough reason, I just pushed commit ab77ad54fef363a090e88681233b4b565734abea please check and confirm that it fixes the problem.

**Comment by alsaleem00** [comment]
yes. it solved the issue. I tried already.

Thanks.
